package testingsentimentanalysis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Phuong Hoang
 */
import DB_Connection.DB_Connection;
import Db_Connection.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import net.proteanit.sql.DbUtils;

public class files extends javax.swing.JFrame {
    private final DB_Connection obj_DB_Connection = new DB_Connection();
    private final Connection conn = obj_DB_Connection.get_connection();
    private final PreparedStatement ps = null;
    /**
     * Creates new form files
     */
    public files() {
        initComponents();
        populateAdminTable();
        
    }
    public void populateAdminTable(){
        try{
            Statement myStmt = conn.createStatement();
            ResultSet myRs = myStmt.executeQuery(
            " SELECT * FROM AllApplied"
            + " WHERE AllApplied.studentID = '" + idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Classes"
            + " WHERE Classes.studentID = '" + idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Housing"
            + " WHERE Housing.studentID = '" + idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Professor"
            + " WHERE Professor.studentID = '" + idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Sports"
            + " WHERE Sports.studentID = '" +idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Environment"
            + " WHERE Environment.studentID = '" + idTxt2.getText() + "'"
            + " UNION"
            + " SELECT * FROM Food"
            + " WHERE Food.studentID = '" + idTxt2.getText() + "'");

            Table_Reviews.setModel(DbUtils.resultSetToTableModel(myRs));
        }
        catch(SQLException e){
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Reviews = new javax.swing.JTable();
        showAllBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addReviewsBtn = new javax.swing.JButton();
        addStudentbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Student = new javax.swing.JTable();
        deleteStudentBtn = new javax.swing.JButton();
        showAllStudentbtn = new javax.swing.JButton();
        idTxt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Section"));

        Table_Reviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reviews", "Student ID", "Topic"
            }
        ));
        jScrollPane1.setViewportView(Table_Reviews);

        showAllBtn.setText("Show All Reviews");
        showAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllBtnMouseClicked(evt);
            }
        });
        showAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Reviews");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addReviewsBtn.setText("Add Reviews");
        addReviewsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReviewsBtnMouseClicked(evt);
            }
        });

        addStudentbtn.setText("Add Student");
        addStudentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentbtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Return to the main page");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        Table_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Reviews Count"
            }
        ));
        jScrollPane2.setViewportView(Table_Student);

        deleteStudentBtn.setText("Delete Student");
        deleteStudentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteStudentBtnMouseClicked(evt);
            }
        });

        showAllStudentbtn.setText("Show All Students");
        showAllStudentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllStudentbtnMouseClicked(evt);
            }
        });
        showAllStudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllStudentbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Student ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(showAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addReviewsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addComponent(deleteStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllStudentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(addReviewsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showAllStudentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(addStudentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAllBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllBtnMouseClicked
        // TODO add your handling code here:
        populateAdminTable();
    }//GEN-LAST:event_showAllBtnMouseClicked

    private void addReviewsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReviewsBtnMouseClicked
        // TODO add your handling code here:
        String id = idTxt2.getText();
        int studentID = Integer.parseInt(id);
        rate r = new rate(studentID);
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_addReviewsBtnMouseClicked

    private void addStudentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentbtnMouseClicked
        // TODO add your handling code here:
        signup s = new signup();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_addStudentbtnMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        main m = new main();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int reviewIDColumn = 1;
        int row = Table_Reviews.getSelectedRow();
        String review = Table_Reviews.getModel().getValueAt(row, reviewIDColumn).toString();
        
        int studentIDColumn = 2;
        String strStudentID = Table_Reviews.getModel().getValueAt(row, studentIDColumn).toString();
        int studentID = Integer.parseInt(strStudentID);
        
        System.out.println(review);
        
        try{
            Database access = new Database();
            access.delete(review, studentID);
        }
        catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void showAllStudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllStudentbtnActionPerformed
        // TODO add your handling code here:
        try{
            Statement myStmt = conn.createStatement();
            ResultSet myRs = myStmt.executeQuery("SELECT * FROM Student");
            Table_Student.setModel(DbUtils.resultSetToTableModel(myRs));
        }
        catch(SQLException e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_showAllStudentbtnActionPerformed

    private void showAllStudentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllStudentbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllStudentbtnMouseClicked

    private void deleteStudentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStudentBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteStudentBtnMouseClicked

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(files.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(files.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(files.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(files.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new files().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Reviews;
    private javax.swing.JTable Table_Student;
    private javax.swing.JButton addReviewsBtn;
    private javax.swing.JButton addStudentbtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JTextField idTxt2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JButton showAllStudentbtn;
    // End of variables declaration//GEN-END:variables
}
